# Generated by Django 4.1.3 on 2023-08-01 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_account_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='amount',
            field=models.IntegerField(),
        ),
    ]
